# Generated by Django 4.1.13 on 2024-03-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsettings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
